name: "TestAction"
on: [ push, pull_request ]
jobs:
  test:
    name: Test actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: acts
      - name: Dump test_credential.json
        id: test_credential
        run: |
          content=`cat acts/test_credential.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=test_credential::$content"

      - uses: ./acts
        with:
          credential: ${{ steps.set_var.test_credential.test_credential }}
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Chmod
        run: chmod +x acts/testproject/gradlew

      - name: Build Test Project
        run: ./gradlew signAllPublications --info
        working-directory: acts/testproject

      - name: Verify
        run: node verify.js
        working-directory: acts/testproject
